<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <RunSettingsFilePath>$(MSBuildProjectDirectory)/.runsettings</RunSettingsFilePath>
    <Nullable>annotations</Nullable>
    <UserSecretsId>bcf43516-1c05-4878-9432-1ad895926d31</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" Version="0.7.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../api/StockHub.csproj" />
  </ItemGroup>
</Project>
