FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-env

COPY api/*.csproj ./api/
COPY ServiceDefaults/*.csproj ./ServiceDefaults/
COPY tests/*.csproj ./tests/
RUN dotnet restore ./tests/

COPY api/ ./api/
COPY ServiceDefaults/ ./ServiceDefaults/
COPY tests/ ./tests/

#Set timezone to HK
ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR ../tests
