pipeline {
    agent any
    
    stages {
        stage('Backup') {
            steps {
                sh 'find . -maxdepth 1 -type f -name "*.pgdump" -delete'
                sh './backup/db_backup.sh'
            }

            post {
                always {
                    archiveArtifacts artifacts: '*.pgdump', fingerprint: true
                }
            }
        }
    }
}
