// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockHub.Database;

#nullable disable

namespace StockHub.Migrations
{
    [DbContext(typeof(StockHubContext))]
    partial class StockHubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockHub.Database.Currency", b =>
                {
                    b.Property<string>("CurrencyId")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("currency_name");

                    b.Property<decimal>("ToUsdRate")
                        .HasColumnType("numeric")
                        .HasColumnName("to_usd_rate");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("CurrencyId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.LogStockTag", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<string>("StockId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<string>("TagCategory")
                        .HasColumnType("text")
                        .HasColumnName("tag_cat");

                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset>("DbUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("db_updated_at");

                    b.Property<string>("Sta")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("sta");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("iden")
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    b.HasKey("Uid", "StockId", "TagCategory", "Tag", "DbUpdatedAt", "Sta");

                    b.HasIndex("Uid", "StockId", "TagCategory", "Tag", "DbUpdatedAt", "Sta");

                    b.ToTable("log_stock_tag", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.Stock", b =>
                {
                    b.Property<string>("StockId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("asset_class");

                    b.Property<decimal?>("Coupon")
                        .HasColumnType("numeric")
                        .HasColumnName("coupon");

                    b.Property<int?>("CouponFreq")
                        .HasColumnType("integer")
                        .HasColumnName("coupon_freq");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DivCrawlDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("div_crawl_date");

                    b.Property<decimal?>("FaceValue")
                        .HasPrecision(6)
                        .HasColumnType("numeric(6,0)")
                        .HasColumnName("face_value");

                    b.Property<DateOnly?>("MaturityDate")
                        .HasColumnType("date")
                        .HasColumnName("maturity_date");

                    b.Property<DateTimeOffset?>("PriceCrawlDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_crawl_date");

                    b.Property<DateOnly?>("PriceMaxDate")
                        .HasColumnType("date")
                        .HasColumnName("price_max_date");

                    b.Property<DateOnly?>("PriceMinDate")
                        .HasColumnType("date")
                        .HasColumnName("price_min_date");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stock_name");

                    b.Property<DateOnly?>("TxMaxDate")
                        .HasColumnType("date")
                        .HasColumnName("tx_max_date");

                    b.Property<DateOnly?>("TxMinDate")
                        .HasColumnType("date")
                        .HasColumnName("tx_min_date");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("StockId");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockDividend", b =>
                {
                    b.Property<string>("StockId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<string>("DividendType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dividend_type");

                    b.Property<string>("DistributionType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("distribution_type");

                    b.Property<DateOnly>("PayableDate")
                        .HasColumnType("date")
                        .HasColumnName("payable_date");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<decimal?>("AmountAdjPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_adj_percentage");

                    b.Property<DateOnly>("AnnounceDate")
                        .HasColumnType("date")
                        .HasColumnName("announce_date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DividendEvent")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dividend_event");

                    b.Property<int>("DividendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dividend_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DividendId"));

                    b.Property<DateOnly>("ExDate")
                        .HasColumnType("date")
                        .HasColumnName("ex_date");

                    b.Property<decimal?>("PrevAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("prev_amount");

                    b.Property<decimal>("ScripPerCount")
                        .HasColumnType("numeric")
                        .HasColumnName("scrip_per_count");

                    b.Property<decimal?>("ScripPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("scrip_price");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("StockId", "DividendType", "DistributionType", "PayableDate");

                    b.HasIndex("Currency");

                    b.HasIndex("StockId", "PayableDate");

                    b.ToTable("stock_dividend", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockPortfolio", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<string>("PortfolioId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<bool>("IsExcludedFromSummary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ex_summary");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_virtual");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("Uid", "PortfolioId");

                    b.HasIndex("DefaultCurrency");

                    b.HasIndex("Uid", "PortfolioId");

                    b.ToTable("stock_portfolio", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockPosition", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<string>("PortfolioId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("StockId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<DateOnly>("ObserveDate")
                        .HasColumnType("date")
                        .HasColumnName("observe_date");

                    b.Property<decimal?>("AverageCost")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("average_cost");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("CurrentGain")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("current_gain");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_latest");

                    b.Property<DateOnly?>("MarketDate")
                        .HasColumnType("date")
                        .HasColumnName("market_date");

                    b.Property<decimal?>("PrevStockPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("prev_stock_price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RealisedAmount")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("realised_amount");

                    b.Property<decimal>("RealisedCost")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("realised_cost");

                    b.Property<decimal>("RealisedDividend")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("realised_dividend");

                    b.Property<decimal>("RealisedGain")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("realised_gain");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("total_cost");

                    b.Property<decimal>("TotalGain")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("total_gain");

                    b.Property<decimal>("UnrealisedAmount")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("unrealised_amount");

                    b.Property<decimal>("UnrealisedCost")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("unrealised_cost");

                    b.Property<decimal>("UnrealisedGain")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("unrealised_gain");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("Uid", "PortfolioId", "StockId", "ObserveDate");

                    b.HasIndex("IsLatest");

                    b.HasIndex("ObserveDate");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.HasIndex("Uid", "ObserveDate");

                    b.HasIndex("Uid", "PortfolioId", "ObserveDate");

                    b.HasIndex("Uid", "PortfolioId", "StockId", "ObserveDate");

                    b.ToTable("stock_position", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockPrice", b =>
                {
                    b.Property<string>("StockId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<DateOnly>("MarketDate")
                        .HasColumnType("date")
                        .HasColumnName("market_date");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("close_price");

                    b.Property<decimal?>("ClosePriceAdj")
                        .HasColumnType("numeric")
                        .HasColumnName("close_price_adj");

                    b.Property<decimal?>("DayHigh")
                        .HasColumnType("numeric")
                        .HasColumnName("day_high");

                    b.Property<decimal?>("DayLow")
                        .HasColumnType("numeric")
                        .HasColumnName("day_low");

                    b.Property<bool>("IsFinalised")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finalised");

                    b.Property<decimal?>("OpenPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("open_price");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("StockId", "MarketDate");

                    b.HasIndex("StockId", "MarketDate")
                        .IsUnique();

                    b.HasIndex("StockId", "MarketDate", "IsFinalised")
                        .IsUnique();

                    b.ToTable("stock_price", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockRealisedScrip", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<string>("PortfolioId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("StockId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<string>("DividendType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dividend_type");

                    b.Property<string>("DistributionType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("distribution_type");

                    b.Property<DateOnly>("PayableDate")
                        .HasColumnType("date")
                        .HasColumnName("payable_date");

                    b.Property<decimal?>("ReinvestPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("reinv_price");

                    b.Property<decimal>("ScripReceived")
                        .HasColumnType("numeric")
                        .HasColumnName("scrip_received");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("Uid", "PortfolioId", "StockId", "DividendType", "DistributionType", "PayableDate");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId", "DividendType", "DistributionType", "PayableDate");

                    b.HasIndex("Uid", "PortfolioId", "StockId", "PayableDate");

                    b.ToTable("stock_realised_scrip", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockTag", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<string>("StockId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<string>("TagCategory")
                        .HasColumnType("text")
                        .HasColumnName("tag_cat");

                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.Property<string>("Sta")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("sta");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("Uid", "StockId", "TagCategory", "Tag");

                    b.HasIndex("StockId");

                    b.HasIndex("Uid", "StockId", "TagCategory", "Tag");

                    b.ToTable("stock_tag", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockTransaction", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.Property<string>("PortfolioId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal?>("AccruedInterest")
                        .HasColumnType("numeric")
                        .HasColumnName("accrued_interest");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("HandlingFee")
                        .HasColumnType("numeric")
                        .HasColumnName("handling_fee");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("numeric")
                        .HasColumnName("tax");

                    b.Property<string>("TranType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tran_type");

                    b.Property<decimal>("TxCount")
                        .HasColumnType("numeric")
                        .HasColumnName("count");

                    b.Property<DateOnly>("TxDate")
                        .HasColumnType("date")
                        .HasColumnName("tx_date");

                    b.Property<decimal>("UnitAmt")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_amt");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal?>("YTM")
                        .HasColumnType("numeric")
                        .HasColumnName("ytm");

                    b.Property<bool>("isTransfer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_transfer");

                    b.HasKey("Uid", "iden", "PortfolioId");

                    b.HasIndex("StockId");

                    b.HasIndex("Uid", "PortfolioId", "StockId", "TxDate");

                    b.ToTable("stock_transaction", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockUser", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<DateTimeOffset?>("LastBeat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_beat");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("Uid");

                    b.HasIndex("Uid");

                    b.ToTable("stock_user", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockVirtualPortfolio", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<string>("PortfolioId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("ChildPortfolioId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("child_portfolio_id");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("Uid", "PortfolioId", "ChildPortfolioId");

                    b.HasIndex("Uid", "ChildPortfolioId");

                    b.HasIndex("Uid", "PortfolioId", "ChildPortfolioId");

                    b.ToTable("stock_virtual_portfolio", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockWatchlist", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uid");

                    b.Property<string>("StockId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("iden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iden"));

                    b.HasKey("Uid", "StockId");

                    b.HasIndex("StockId");

                    b.HasIndex("Uid", "StockId");

                    b.ToTable("stock_watchlist", (string)null);
                });

            modelBuilder.Entity("StockHub.Database.StockDividend", b =>
                {
                    b.HasOne("StockHub.Database.Currency", "FkCurrency")
                        .WithMany("FkStockDividends")
                        .HasForeignKey("Currency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockHub.Database.Stock", "FkStock")
                        .WithMany("FkStockDividends")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkCurrency");

                    b.Navigation("FkStock");
                });

            modelBuilder.Entity("StockHub.Database.StockPortfolio", b =>
                {
                    b.HasOne("StockHub.Database.Currency", "FkDefaultCurrency")
                        .WithMany("FkStockPortfolios")
                        .HasForeignKey("DefaultCurrency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkDefaultCurrency");
                });

            modelBuilder.Entity("StockHub.Database.StockPosition", b =>
                {
                    b.HasOne("StockHub.Database.StockPortfolio", "FkStockPortfolio")
                        .WithMany("FkStockPositions")
                        .HasForeignKey("PortfolioId")
                        .HasPrincipalKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockHub.Database.Stock", "FkStock")
                        .WithMany("FkStockPositions")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkStock");

                    b.Navigation("FkStockPortfolio");
                });

            modelBuilder.Entity("StockHub.Database.StockPrice", b =>
                {
                    b.HasOne("StockHub.Database.Stock", "FkStock")
                        .WithMany("FkStockPrices")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkStock");
                });

            modelBuilder.Entity("StockHub.Database.StockRealisedScrip", b =>
                {
                    b.HasOne("StockHub.Database.StockPortfolio", "FkStockPortfolio")
                        .WithMany("FkStockRealisedScrips")
                        .HasForeignKey("PortfolioId")
                        .HasPrincipalKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockHub.Database.StockDividend", "FkStockDividend")
                        .WithMany("FkStockRealisedScrips")
                        .HasForeignKey("StockId", "DividendType", "DistributionType", "PayableDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkStockDividend");

                    b.Navigation("FkStockPortfolio");
                });

            modelBuilder.Entity("StockHub.Database.StockTag", b =>
                {
                    b.HasOne("StockHub.Database.Stock", "FkStock")
                        .WithMany("FkStockTags")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkStock");
                });

            modelBuilder.Entity("StockHub.Database.StockTransaction", b =>
                {
                    b.HasOne("StockHub.Database.Stock", "FkStock")
                        .WithMany("FkStockTransactions")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockHub.Database.StockPortfolio", "FkStockPortfolio")
                        .WithMany("FkStockTransactions")
                        .HasForeignKey("Uid", "PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkStock");

                    b.Navigation("FkStockPortfolio");
                });

            modelBuilder.Entity("StockHub.Database.StockVirtualPortfolio", b =>
                {
                    b.HasOne("StockHub.Database.StockPortfolio", "FkChildPortfolio")
                        .WithMany("FkStockVirtualChildPortfolios")
                        .HasForeignKey("Uid", "ChildPortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockHub.Database.StockPortfolio", "FkPortfolio")
                        .WithMany("FkStockVirtualPortfolios")
                        .HasForeignKey("Uid", "PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkChildPortfolio");

                    b.Navigation("FkPortfolio");
                });

            modelBuilder.Entity("StockHub.Database.StockWatchlist", b =>
                {
                    b.HasOne("StockHub.Database.Stock", "FkStock")
                        .WithMany("FkStockWatchlists")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkStock");
                });

            modelBuilder.Entity("StockHub.Database.Currency", b =>
                {
                    b.Navigation("FkStockDividends");

                    b.Navigation("FkStockPortfolios");
                });

            modelBuilder.Entity("StockHub.Database.Stock", b =>
                {
                    b.Navigation("FkStockDividends");

                    b.Navigation("FkStockPositions");

                    b.Navigation("FkStockPrices");

                    b.Navigation("FkStockTags");

                    b.Navigation("FkStockTransactions");

                    b.Navigation("FkStockWatchlists");
                });

            modelBuilder.Entity("StockHub.Database.StockDividend", b =>
                {
                    b.Navigation("FkStockRealisedScrips");
                });

            modelBuilder.Entity("StockHub.Database.StockPortfolio", b =>
                {
                    b.Navigation("FkStockPositions");

                    b.Navigation("FkStockRealisedScrips");

                    b.Navigation("FkStockTransactions");

                    b.Navigation("FkStockVirtualChildPortfolios");

                    b.Navigation("FkStockVirtualPortfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
