-- Create the database
CREATE DATABASE sh_demo;

-- Connect to the newly created database
\c sh_demo;

--
-- PostgreSQL database dump
--

\restrict wlrnbuCy2sVr5GpbLbG0ik1bG40mn5z1KYm9utCdmchIRh6rZ2jRnTFu7HuU7AH

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pgadmin
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO pgadmin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: stock_transaction; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_transaction (
    stock_id character varying(20) DEFAULT ''::text NOT NULL,
    unit_amt numeric NOT NULL,
    count numeric NOT NULL,
    tx_date date NOT NULL,
    iden integer NOT NULL,
    tran_type character varying(10) DEFAULT ''::text NOT NULL,
    portfolio_id character varying(20) NOT NULL,
    currency character varying(3) DEFAULT ''::text NOT NULL,
    handling_fee numeric DEFAULT 0.0,
    uid character varying(40) NOT NULL,
    comment text,
    accrued_interest numeric,
    ytm numeric,
    is_transfer boolean DEFAULT false NOT NULL,
    tax numeric
);


ALTER TABLE public.stock_transaction OWNER TO pgadmin;

--
-- Name: StockTransactions_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_transaction ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StockTransactions_iden_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO pgadmin;

--
-- Name: currency; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.currency (
    currency_id character varying(3) NOT NULL,
    iden integer NOT NULL,
    currency_name character varying(40),
    to_usd_rate numeric NOT NULL
);


ALTER TABLE public.currency OWNER TO pgadmin;

--
-- Name: currency_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.currency ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: log_stock_tag; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.log_stock_tag (
    uid character varying(40) NOT NULL,
    stock_id character varying(20) NOT NULL,
    tag_cat text NOT NULL,
    tag text NOT NULL,
    updated_at timestamp with time zone,
    sta character varying(5) NOT NULL,
    iden integer NOT NULL,
    percentage numeric NOT NULL,
    color text DEFAULT ''::text NOT NULL,
    db_updated_at timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public.log_stock_tag OWNER TO pgadmin;

--
-- Name: stock; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock (
    stock_id character varying(20) NOT NULL,
    iden integer NOT NULL,
    stock_name character varying(80) DEFAULT ''::text NOT NULL,
    currency character varying(3) DEFAULT ''::text NOT NULL,
    div_crawl_date timestamp with time zone,
    price_crawl_date timestamp with time zone,
    asset_class character varying(10) DEFAULT ''::character varying NOT NULL,
    coupon numeric DEFAULT 0.0,
    maturity_date date,
    price_max_date date,
    price_min_date date,
    tx_max_date date,
    tx_min_date date,
    coupon_freq integer,
    face_value numeric(6,0)
);


ALTER TABLE public.stock OWNER TO pgadmin;

--
-- Name: stock_dividend; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_dividend (
    stock_id character varying(20) NOT NULL,
    announce_date date NOT NULL,
    dividend_type character varying(10) NOT NULL,
    dividend_event character varying(10) DEFAULT ''::character varying NOT NULL,
    amount numeric DEFAULT 0.0 NOT NULL,
    ex_date date NOT NULL,
    payable_date date NOT NULL,
    distribution_type character varying(10) DEFAULT ''::text NOT NULL,
    scrip_price numeric DEFAULT 0.0,
    dividend_id integer NOT NULL,
    scrip_per_count numeric DEFAULT 0.0 NOT NULL,
    currency character varying(3) DEFAULT ''::text NOT NULL,
    amount_adj_percentage numeric,
    prev_amount numeric
);


ALTER TABLE public.stock_dividend OWNER TO pgadmin;

--
-- Name: stock_dividend_dividend_id_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_dividend ALTER COLUMN dividend_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_dividend_dividend_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_portfolio; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_portfolio (
    portfolio_id character varying(20) NOT NULL,
    iden integer NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    default_currency character varying(3) DEFAULT ''::text NOT NULL,
    uid character varying(40) NOT NULL,
    is_ex_summary boolean DEFAULT false NOT NULL,
    is_virtual boolean DEFAULT false NOT NULL
);


ALTER TABLE public.stock_portfolio OWNER TO pgadmin;

--
-- Name: stock_portfolio_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_portfolio ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_portfolio_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_position; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_position (
    uid character varying(40) NOT NULL,
    portfolio_id character varying(20) NOT NULL,
    stock_id character varying(20) NOT NULL,
    iden integer NOT NULL,
    quantity numeric NOT NULL,
    currency character varying(3) DEFAULT ''::text NOT NULL,
    realised_amount numeric(10,4) DEFAULT 0.0 NOT NULL,
    realised_cost numeric(10,4) DEFAULT 0.0 NOT NULL,
    realised_dividend numeric(10,4) DEFAULT 0.0 NOT NULL,
    realised_gain numeric(10,4) DEFAULT 0.0 NOT NULL,
    total_cost numeric(10,4) DEFAULT 0.0 NOT NULL,
    observe_date date DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    is_latest boolean DEFAULT false NOT NULL,
    average_cost numeric(10,4),
    total_gain numeric(10,4) DEFAULT 0.0 NOT NULL,
    unrealised_amount numeric(10,4) DEFAULT 0.0 NOT NULL,
    unrealised_cost numeric(10,4) DEFAULT 0.0 NOT NULL,
    unrealised_gain numeric(10,4) DEFAULT 0.0 NOT NULL,
    current_gain numeric(10,4) DEFAULT 0.0 NOT NULL,
    prev_stock_price numeric(10,4) DEFAULT 0.0,
    market_date date
);


ALTER TABLE public.stock_position OWNER TO pgadmin;

--
-- Name: stock_price; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_price (
    stock_id character varying(20) NOT NULL,
    market_date date NOT NULL,
    open_price numeric,
    day_high numeric,
    day_low numeric,
    close_price numeric NOT NULL,
    close_price_adj numeric,
    volume numeric,
    is_finalised boolean DEFAULT false NOT NULL,
    iden integer NOT NULL
);


ALTER TABLE public.stock_price OWNER TO pgadmin;

--
-- Name: stock_price_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_price ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_price_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_realised_scrip; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_realised_scrip (
    stock_id character varying(20) NOT NULL,
    dividend_type character varying(10) NOT NULL,
    distribution_type character varying(10) NOT NULL,
    payable_date date NOT NULL,
    iden integer NOT NULL,
    scrip_received numeric NOT NULL,
    portfolio_id character varying(20) NOT NULL,
    uid character varying(40) NOT NULL,
    reinv_price numeric
);


ALTER TABLE public.stock_realised_scrip OWNER TO pgadmin;

--
-- Name: stock_realised_scrip_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_realised_scrip ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_realised_scrip_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_tag; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_tag (
    uid character varying(40) NOT NULL,
    stock_id character varying(20) NOT NULL,
    tag_cat text NOT NULL,
    tag text NOT NULL,
    iden integer NOT NULL,
    percentage numeric NOT NULL,
    color text,
    sta character varying(5),
    updated_at timestamp with time zone DEFAULT '-infinity'::timestamp with time zone
);


ALTER TABLE public.stock_tag OWNER TO pgadmin;

--
-- Name: stock_tag_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_tag ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_tag_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_unrealised_position_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_position ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_unrealised_position_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_user; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_user (
    uid character varying(40) NOT NULL,
    iden integer NOT NULL,
    last_beat timestamp with time zone
);


ALTER TABLE public.stock_user OWNER TO pgadmin;

--
-- Name: stock_user_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_user ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_user_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_virtual_portfolio; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_virtual_portfolio (
    uid character varying(40) NOT NULL,
    portfolio_id character varying(20) NOT NULL,
    child_portfolio_id character varying(20) NOT NULL,
    iden integer NOT NULL
);


ALTER TABLE public.stock_virtual_portfolio OWNER TO pgadmin;

--
-- Name: stock_virtual_portfolio_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_virtual_portfolio ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_virtual_portfolio_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_watchlist; Type: TABLE; Schema: public; Owner: pgadmin
--

CREATE TABLE public.stock_watchlist (
    stock_id character varying(20) NOT NULL,
    iden integer NOT NULL,
    priority integer NOT NULL,
    uid character varying(40) DEFAULT ''::text NOT NULL
);


ALTER TABLE public.stock_watchlist OWNER TO pgadmin;

--
-- Name: stock_watchlist_iden_seq; Type: SEQUENCE; Schema: public; Owner: pgadmin
--

ALTER TABLE public.stock_watchlist ALTER COLUMN iden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_watchlist_iden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_portfolio AK_stock_portfolio_portfolio_id; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_portfolio
    ADD CONSTRAINT "AK_stock_portfolio_portfolio_id" UNIQUE (portfolio_id);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: currency PK_currency; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT "PK_currency" PRIMARY KEY (currency_id);


--
-- Name: log_stock_tag PK_log_stock_tag; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.log_stock_tag
    ADD CONSTRAINT "PK_log_stock_tag" PRIMARY KEY (uid, stock_id, tag_cat, tag, db_updated_at, sta);


--
-- Name: stock PK_stock; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT "PK_stock" PRIMARY KEY (stock_id);


--
-- Name: stock_dividend PK_stock_dividend; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_dividend
    ADD CONSTRAINT "PK_stock_dividend" PRIMARY KEY (stock_id, dividend_type, distribution_type, payable_date);


--
-- Name: stock_portfolio PK_stock_portfolio; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_portfolio
    ADD CONSTRAINT "PK_stock_portfolio" PRIMARY KEY (uid, portfolio_id);


--
-- Name: stock_position PK_stock_position; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_position
    ADD CONSTRAINT "PK_stock_position" PRIMARY KEY (uid, portfolio_id, stock_id, observe_date);


--
-- Name: stock_price PK_stock_price; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_price
    ADD CONSTRAINT "PK_stock_price" PRIMARY KEY (stock_id, market_date);


--
-- Name: stock_realised_scrip PK_stock_realised_scrip; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_realised_scrip
    ADD CONSTRAINT "PK_stock_realised_scrip" PRIMARY KEY (uid, portfolio_id, stock_id, dividend_type, distribution_type, payable_date);


--
-- Name: stock_tag PK_stock_tag; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_tag
    ADD CONSTRAINT "PK_stock_tag" PRIMARY KEY (uid, stock_id, tag_cat, tag);


--
-- Name: stock_transaction PK_stock_transaction; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_transaction
    ADD CONSTRAINT "PK_stock_transaction" PRIMARY KEY (uid, iden, portfolio_id);


--
-- Name: stock_user PK_stock_user; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_user
    ADD CONSTRAINT "PK_stock_user" PRIMARY KEY (uid);


--
-- Name: stock_virtual_portfolio PK_stock_virtual_portfolio; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_virtual_portfolio
    ADD CONSTRAINT "PK_stock_virtual_portfolio" PRIMARY KEY (uid, portfolio_id, child_portfolio_id);


--
-- Name: stock_watchlist PK_stock_watchlist; Type: CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_watchlist
    ADD CONSTRAINT "PK_stock_watchlist" PRIMARY KEY (uid, stock_id);


--
-- Name: IX_currency_currency_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_currency_currency_id" ON public.currency USING btree (currency_id);


--
-- Name: IX_log_stock_tag_uid_stock_id_tag_cat_tag_db_updated_at_sta; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_log_stock_tag_uid_stock_id_tag_cat_tag_db_updated_at_sta" ON public.log_stock_tag USING btree (uid, stock_id, tag_cat, tag, db_updated_at, sta);


--
-- Name: IX_stock_dividend_currency; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_dividend_currency" ON public.stock_dividend USING btree (currency);


--
-- Name: IX_stock_dividend_stock_id_payable_date; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_dividend_stock_id_payable_date" ON public.stock_dividend USING btree (stock_id, payable_date);


--
-- Name: IX_stock_portfolio_default_currency; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_portfolio_default_currency" ON public.stock_portfolio USING btree (default_currency);


--
-- Name: IX_stock_portfolio_uid_portfolio_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_portfolio_uid_portfolio_id" ON public.stock_portfolio USING btree (uid, portfolio_id);


--
-- Name: IX_stock_position_is_latest; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_position_is_latest" ON public.stock_position USING btree (is_latest);


--
-- Name: IX_stock_position_observe_date; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_position_observe_date" ON public.stock_position USING btree (observe_date);


--
-- Name: IX_stock_position_portfolio_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_position_portfolio_id" ON public.stock_position USING btree (portfolio_id);


--
-- Name: IX_stock_position_stock_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_position_stock_id" ON public.stock_position USING btree (stock_id);


--
-- Name: IX_stock_position_uid_observe_date; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_position_uid_observe_date" ON public.stock_position USING btree (uid, observe_date);


--
-- Name: IX_stock_position_uid_portfolio_id_observe_date; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_position_uid_portfolio_id_observe_date" ON public.stock_position USING btree (uid, portfolio_id, observe_date);


--
-- Name: IX_stock_position_uid_portfolio_id_stock_id_observe_date; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_position_uid_portfolio_id_stock_id_observe_date" ON public.stock_position USING btree (uid, portfolio_id, stock_id, observe_date);


--
-- Name: IX_stock_price_stock_id_market_date; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE UNIQUE INDEX "IX_stock_price_stock_id_market_date" ON public.stock_price USING btree (stock_id, market_date);


--
-- Name: IX_stock_price_stock_id_market_date_is_finalised; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE UNIQUE INDEX "IX_stock_price_stock_id_market_date_is_finalised" ON public.stock_price USING btree (stock_id, market_date, is_finalised);


--
-- Name: IX_stock_realised_scrip_portfolio_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_realised_scrip_portfolio_id" ON public.stock_realised_scrip USING btree (portfolio_id);


--
-- Name: IX_stock_realised_scrip_stock_id_dividend_type_distribution_ty~; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_realised_scrip_stock_id_dividend_type_distribution_ty~" ON public.stock_realised_scrip USING btree (stock_id, dividend_type, distribution_type, payable_date);


--
-- Name: IX_stock_realised_scrip_uid_portfolio_id_stock_id_payable_date; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_realised_scrip_uid_portfolio_id_stock_id_payable_date" ON public.stock_realised_scrip USING btree (uid, portfolio_id, stock_id, payable_date);


--
-- Name: IX_stock_stock_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE UNIQUE INDEX "IX_stock_stock_id" ON public.stock USING btree (stock_id);


--
-- Name: IX_stock_tag_stock_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_tag_stock_id" ON public.stock_tag USING btree (stock_id);


--
-- Name: IX_stock_tag_uid_stock_id_tag_cat_tag; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_tag_uid_stock_id_tag_cat_tag" ON public.stock_tag USING btree (uid, stock_id, tag_cat, tag);


--
-- Name: IX_stock_transaction_stock_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_transaction_stock_id" ON public.stock_transaction USING btree (stock_id);


--
-- Name: IX_stock_transaction_uid_portfolio_id_stock_id_tx_date; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_transaction_uid_portfolio_id_stock_id_tx_date" ON public.stock_transaction USING btree (uid, portfolio_id, stock_id, tx_date);


--
-- Name: IX_stock_user_uid; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_user_uid" ON public.stock_user USING btree (uid);


--
-- Name: IX_stock_virtual_portfolio_uid_child_portfolio_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_virtual_portfolio_uid_child_portfolio_id" ON public.stock_virtual_portfolio USING btree (uid, child_portfolio_id);


--
-- Name: IX_stock_virtual_portfolio_uid_portfolio_id_child_portfolio_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_virtual_portfolio_uid_portfolio_id_child_portfolio_id" ON public.stock_virtual_portfolio USING btree (uid, portfolio_id, child_portfolio_id);


--
-- Name: IX_stock_watchlist_stock_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_watchlist_stock_id" ON public.stock_watchlist USING btree (stock_id);


--
-- Name: IX_stock_watchlist_uid_stock_id; Type: INDEX; Schema: public; Owner: pgadmin
--

CREATE INDEX "IX_stock_watchlist_uid_stock_id" ON public.stock_watchlist USING btree (uid, stock_id);


--
-- Name: stock_dividend FK_stock_dividend_currency_currency; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_dividend
    ADD CONSTRAINT "FK_stock_dividend_currency_currency" FOREIGN KEY (currency) REFERENCES public.currency(currency_id) ON DELETE CASCADE;


--
-- Name: stock_dividend FK_stock_dividend_stock_stock_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_dividend
    ADD CONSTRAINT "FK_stock_dividend_stock_stock_id" FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id) ON DELETE CASCADE;


--
-- Name: stock_portfolio FK_stock_portfolio_currency_default_currency; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_portfolio
    ADD CONSTRAINT "FK_stock_portfolio_currency_default_currency" FOREIGN KEY (default_currency) REFERENCES public.currency(currency_id) ON DELETE CASCADE;


--
-- Name: stock_position FK_stock_position_stock_portfolio_portfolio_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_position
    ADD CONSTRAINT "FK_stock_position_stock_portfolio_portfolio_id" FOREIGN KEY (portfolio_id) REFERENCES public.stock_portfolio(portfolio_id) ON DELETE CASCADE;


--
-- Name: stock_position FK_stock_position_stock_stock_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_position
    ADD CONSTRAINT "FK_stock_position_stock_stock_id" FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id) ON DELETE CASCADE;


--
-- Name: stock_price FK_stock_price_stock_stock_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_price
    ADD CONSTRAINT "FK_stock_price_stock_stock_id" FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id) ON DELETE CASCADE;


--
-- Name: stock_realised_scrip FK_stock_realised_scrip_stock_dividend_stock_id_dividend_type_~; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_realised_scrip
    ADD CONSTRAINT "FK_stock_realised_scrip_stock_dividend_stock_id_dividend_type_~" FOREIGN KEY (stock_id, dividend_type, distribution_type, payable_date) REFERENCES public.stock_dividend(stock_id, dividend_type, distribution_type, payable_date) ON DELETE CASCADE;


--
-- Name: stock_realised_scrip FK_stock_realised_scrip_stock_portfolio_portfolio_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_realised_scrip
    ADD CONSTRAINT "FK_stock_realised_scrip_stock_portfolio_portfolio_id" FOREIGN KEY (portfolio_id) REFERENCES public.stock_portfolio(portfolio_id) ON DELETE CASCADE;


--
-- Name: stock_tag FK_stock_tag_stock_stock_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_tag
    ADD CONSTRAINT "FK_stock_tag_stock_stock_id" FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id) ON DELETE CASCADE;


--
-- Name: stock_transaction FK_stock_transaction_stock_portfolio_uid_portfolio_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_transaction
    ADD CONSTRAINT "FK_stock_transaction_stock_portfolio_uid_portfolio_id" FOREIGN KEY (uid, portfolio_id) REFERENCES public.stock_portfolio(uid, portfolio_id) ON DELETE CASCADE;


--
-- Name: stock_transaction FK_stock_transaction_stock_stock_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_transaction
    ADD CONSTRAINT "FK_stock_transaction_stock_stock_id" FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id) ON DELETE CASCADE;


--
-- Name: stock_virtual_portfolio FK_stock_virtual_portfolio_stock_portfolio_uid_child_portfolio~; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_virtual_portfolio
    ADD CONSTRAINT "FK_stock_virtual_portfolio_stock_portfolio_uid_child_portfolio~" FOREIGN KEY (uid, child_portfolio_id) REFERENCES public.stock_portfolio(uid, portfolio_id) ON DELETE CASCADE;


--
-- Name: stock_virtual_portfolio FK_stock_virtual_portfolio_stock_portfolio_uid_portfolio_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_virtual_portfolio
    ADD CONSTRAINT "FK_stock_virtual_portfolio_stock_portfolio_uid_portfolio_id" FOREIGN KEY (uid, portfolio_id) REFERENCES public.stock_portfolio(uid, portfolio_id) ON DELETE CASCADE;


--
-- Name: stock_watchlist FK_stock_watchlist_stock_stock_id; Type: FK CONSTRAINT; Schema: public; Owner: pgadmin
--

ALTER TABLE ONLY public.stock_watchlist
    ADD CONSTRAINT "FK_stock_watchlist_stock_stock_id" FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id) ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pgadmin
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict wlrnbuCy2sVr5GpbLbG0ik1bG40mn5z1KYm9utCdmchIRh6rZ2jRnTFu7HuU7AH

