# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import yfinance_pb2 as yfinance__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in yfinance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YFinanceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHistory = channel.unary_unary(
                '/yfinance.YFinanceService/GetHistory',
                request_serializer=yfinance__pb2.HistoryRequest.SerializeToString,
                response_deserializer=yfinance__pb2.CsvResponse.FromString,
                _registered_method=True)
        self.GetDividends = channel.unary_unary(
                '/yfinance.YFinanceService/GetDividends',
                request_serializer=yfinance__pb2.DividendRequest.SerializeToString,
                response_deserializer=yfinance__pb2.CsvResponse.FromString,
                _registered_method=True)
        self.HealthTest = channel.unary_unary(
                '/yfinance.YFinanceService/HealthTest',
                request_serializer=yfinance__pb2.HealthRequest.SerializeToString,
                response_deserializer=yfinance__pb2.HealthResponse.FromString,
                _registered_method=True)


class YFinanceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDividends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YFinanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=yfinance__pb2.HistoryRequest.FromString,
                    response_serializer=yfinance__pb2.CsvResponse.SerializeToString,
            ),
            'GetDividends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDividends,
                    request_deserializer=yfinance__pb2.DividendRequest.FromString,
                    response_serializer=yfinance__pb2.CsvResponse.SerializeToString,
            ),
            'HealthTest': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthTest,
                    request_deserializer=yfinance__pb2.HealthRequest.FromString,
                    response_serializer=yfinance__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yfinance.YFinanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yfinance.YFinanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class YFinanceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yfinance.YFinanceService/GetHistory',
            yfinance__pb2.HistoryRequest.SerializeToString,
            yfinance__pb2.CsvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDividends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yfinance.YFinanceService/GetDividends',
            yfinance__pb2.DividendRequest.SerializeToString,
            yfinance__pb2.CsvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yfinance.YFinanceService/HealthTest',
            yfinance__pb2.HealthRequest.SerializeToString,
            yfinance__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
