# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yfinance.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'yfinance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eyfinance.proto\x12\x08yfinance\"F\n\x0eHistoryRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"!\n\x0f\x44ividendRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1f\n\x0b\x43svResponse\x12\x10\n\x08\x63sv_data\x18\x01 \x01(\t2\xd3\x01\n\x0fYFinanceService\x12=\n\nGetHistory\x12\x18.yfinance.HistoryRequest\x1a\x15.yfinance.CsvResponse\x12@\n\x0cGetDividends\x12\x19.yfinance.DividendRequest\x1a\x15.yfinance.CsvResponse\x12?\n\nHealthTest\x12\x17.yfinance.HealthRequest\x1a\x18.yfinance.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yfinance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTORYREQUEST']._serialized_start=28
  _globals['_HISTORYREQUEST']._serialized_end=98
  _globals['_DIVIDENDREQUEST']._serialized_start=100
  _globals['_DIVIDENDREQUEST']._serialized_end=133
  _globals['_HEALTHREQUEST']._serialized_start=135
  _globals['_HEALTHREQUEST']._serialized_end=150
  _globals['_HEALTHRESPONSE']._serialized_start=152
  _globals['_HEALTHRESPONSE']._serialized_end=184
  _globals['_CSVRESPONSE']._serialized_start=186
  _globals['_CSVRESPONSE']._serialized_end=217
  _globals['_YFINANCESERVICE']._serialized_start=220
  _globals['_YFINANCESERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
