version: '3.7'

services:
  api:
    container_name: sh-demo-api
    build: ../api/
    ports: #HOST:CONTAINER
      - 4000:4000
    environment:
      - DATABASE_CONSTR=User ID=pgadmin;Password=temp_password;Host=sh-pgdb;Port=5432;Database=sh_demo;
      - STOCKHUB_API_PY_BASE_URL=${STOCKHUB_API_PY_BASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4000 #Bind all interfaces
      - CORS_ORIGINS=http://localhost:3000;http://127.0.0.1:3000
    restart: unless-stopped
  pg:
    container_name: sh-pgdb
    image: postgres:18
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=temp_password
      - POSTGRES_DB=postgres
      - TZ=Asia/Hong_Kong
      - PGTZ=Asia/Hong_Kong
    volumes:
      - type: bind
        source: ./DatabaseSeed/
        target: /docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    restart: unless-stopped
